# Generated by Django 6.0.1 on 2026-02-18 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_membership_created_at_membership_invite_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temp_role', models.CharField(choices=[('instructor', 'instructor'), ('admin', 'admin')], help_text='The elevated role being granted.', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for a permanent delegation. Set a datetime for auto-expiry.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to revoke access without deleting the record.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Automatically set when is_active is flipped to False.', null=True)),
                ('reason', models.TextField(blank=True, help_text='Optional note explaining why this delegation was granted.')),
                ('granted_by', models.ForeignKey(help_text='The Org admin or superuser who approved this', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_granted', to=settings.AUTH_USER_MODEL)),
                ('granted_to', models.ForeignKey(help_text='The User receiving elevated access', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='users.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['granted_to', 'organization', 'is_active'], name='users_deleg_granted_72e073_idx')],
            },
        ),
    ]
