# Generated by Django 6.0.1 on 2026-03-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delegation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='organization',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
