# Generated by Django 6.0.2 on 2026-02-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_module_lesson_lessonstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
