# Generated by Django 6.0.1 on 2026-02-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_course_category_course_level_alter_course_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
