# Generated by Django 6.0.1 on 2026-02-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_lesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allows_installments',
            field=models.BooleanField(default=False, help_text='Can students pay in installments?'),
        ),
        migrations.AddField(
            model_name='course',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount per installment (auto-calculated if blank)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='installment_count',
            field=models.PositiveIntegerField(default=1, help_text='How many installments are allowed'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
