# Generated by Django 6.0.1 on 2026-02-19 14:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_course_allows_installments_course_installment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
