# Generated by Django 6.0.1 on 2026-02-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_lesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
